import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "You Account",
  description: "Generated by create next app",
};
export default function AccountLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen ">
      <main className="flex flex-col flex-1">{children}</main>
    </div>
  );
}
