import Footer from "@/components/shared/Footer";
import Header from "@/components/shared/header/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Amazon App",
  description: "Generated by create next app",
};
export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen ">
      <Header />
      <main className="flex flex-col flex-1">{children}</main>
      <Footer />
    </div>
  );
}
